name: Auto Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */36 * * *'

jobs:
  auto-update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.1]
    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Updating latest stats
        run: bin/update-stats

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Stats Update

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
            token: ${{ secrets.BLADE_ICONS_PACKAGES_REPO_ACCESS_TOKEN }}
            repository: codeat3/blade-icons-packages
            event-type: collection-updated
            client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
